package org.primaldev.ppm.ui.task;

import java.util.List;

import org.activiti.engine.task.Task;
import org.primaldev.ppm.util.ProcessUtil;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

public class TaskEventHistoryForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextArea eventText;
	@AutoGenerated
	private Button closeButton;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	Window mywindow;
	Task task;
	public TaskEventHistoryForm(Window mywindow, Task task) {
		this.task=task;
		this.mywindow = mywindow;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		addClickListeners();
		initTable();
	}
	
	
	private void initTable(){
		List<org.activiti.engine.task.Event> events = ProcessUtil.getTaskService().getTaskEvents(task.getId());
		for (org.activiti.engine.task.Event event:events) {
			eventText.setValue("\n" + event.getAction() + ": " + event.getMessage() + eventText.getValue());
		}
		
	}
	
	
	private void addClickListeners(){
		closeButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().removeWindow(mywindow);
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("600px");
		mainLayout.setHeight("640px");
		
		// top-level component properties
		setWidth("600px");
		setHeight("640px");
		
		// closeButton
		closeButton = new Button();
		closeButton.setCaption("Close");
		closeButton.setImmediate(true);
		closeButton.setWidth("-1px");
		closeButton.setHeight("-1px");
		mainLayout.addComponent(closeButton, "top:580.0px;left:260.0px;");
		
		// eventText
		eventText = new TextArea();
		eventText.setCaption("events");
		eventText.setImmediate(false);
		eventText.setWidth("560px");
		eventText.setHeight("540px");
		mainLayout.addComponent(eventText, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

}
