package org.primaldev.ppm;

import javax.servlet.annotation.WebServlet;

import org.activiti.engine.IdentityService;
import org.activiti.engine.ProcessEngines;
import org.primaldev.ppm.ui.main.MainUI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.navigator.Navigator;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

@SuppressWarnings("serial")
@Theme("packageprocessmanager")
public class PackageprocessmanagerUI extends UI {
	Navigator navigator;
	protected static final String MAINVIEW = "main";
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button loginButton;
	@AutoGenerated
	private PasswordField passWord;
	@AutoGenerated
	private TextField userName;
	
	
	//private LoginUI loginUI = new LoginUI();
	
	@WebServlet(value = "/*", asyncSupported = true)
	@VaadinServletConfiguration(productionMode = false, ui = PackageprocessmanagerUI.class)
	public static class Servlet extends VaadinServlet {
	}

	@Override
	protected void init(VaadinRequest request) {
		//final VerticalLayout layout = new VerticalLayout();
		//navigator = new Navigator(this, this);
		//layout.setMargin(true);
		
		buildMainLayout();
		addClicklisteners();
		
		
		
		
		setContent(mainLayout);
	//	setSizeFull();
		//setContent(loginUI);
		
		
		
		//navigator.addView("", new LoginUI(navigator)); //default fallback view required
		//navigator.addView(MAINVIEW, new MainUI());
		
		
		
		//setContent(layout);
		

		//setContent(loginUI);

		/*Button button = new Button("Click Me");
		button.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				layout.addComponent(new Label("Thank you for clicking"));
			}
		});
		layout.addComponent(button);
		*/
	}
	
	@SuppressWarnings("serial")
	private void addClicklisteners() {
		loginButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if (getIdentityService().checkPassword(userName.getValue(), passWord.getValue())) {
					getIdentityService().setAuthenticatedUserId(userName.getValue());					
					//fireViewEvent(new UserLoggedInEvent(getView(), userName.getValue()));
					getSession().setAttribute("user", userName.getValue());
					showLoginGood();
					setContent(new MainUI());			
				} else {
					
					clearForm();
				    showLoginFailed();
				}
			}
		});
	}
	
	private IdentityService getIdentityService() {
		return ProcessEngines.getDefaultProcessEngine().getIdentityService();
	}
	
	
	public void showLoginFailed() {
		
		Notification.show("Login Status",
                "Login failed. Please try again.",
                Notification.Type.TRAY_NOTIFICATION);
	}
	
	public void showLoginGood() {
		
		Notification.show("Login Successfull",
                "Welcome...",
                Notification.Type.TRAY_NOTIFICATION);
	}


	public void clearForm() {
		userName.setValue("");
		passWord.setValue("");
		userName.focus();
	}
	
	
	@AutoGenerated	
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// userName
		userName = new TextField();
		userName.setCaption("User Name");
		userName.setImmediate(false);
		userName.setWidth("180px");
		userName.setHeight("-1px");
		mainLayout.addComponent(userName, "top:176.0px;left:260.0px;");
		
		// passWord
		passWord = new PasswordField();
		passWord.setCaption("Password");
		passWord.setImmediate(false);
		passWord.setWidth("180px");
		passWord.setHeight("-1px");
		mainLayout.addComponent(passWord, "top:220.0px;left:260.0px;");
		
		// loginButton
		loginButton = new Button();
		loginButton.setCaption("Login");
		loginButton.setImmediate(true);
		loginButton.setWidth("-1px");
		loginButton.setHeight("-1px");
		mainLayout.addComponent(loginButton, "top:260.0px;left:380.0px;");
		
		return mainLayout;
	}

}