package org.primaldev.ppm.ui.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.themes.Reindeer;

public class WelcomeSummaryUI extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout taskSummaryLayout;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	Label myTasks;
	
	public WelcomeSummaryUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setSummary();
		setStyle();
		addClickListeners();
	}

	private void setStyle(){
		taskSummaryLayout.setStyleName(Reindeer.LAYOUT_WHITE);
	}
	
	@SuppressWarnings("serial")
	private void addClickListeners(){
	
		
	}
	
	private void setSummary(){
		Label myTasks = new Label();
		
		taskSummaryLayout.addComponent(myTasks);
		
		
	}
	
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// taskSummaryLayout
		taskSummaryLayout = new AbsoluteLayout();
		taskSummaryLayout.setCaption("Summary");
		taskSummaryLayout.setImmediate(false);
		taskSummaryLayout.setWidth("280px");
		taskSummaryLayout.setHeight("360px");
		mainLayout.addComponent(taskSummaryLayout, "top:100.0px;left:60.0px;");
		
		return mainLayout;
	}

}
