package org.primaldev.ppm.ui.task.history;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Table;

public class TaskHistory extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static final String NAME = "TaskHistory";
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table historyTable;
	@AutoGenerated
	private InlineDateField toDate;
	@AutoGenerated
	private InlineDateField fromDate;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TaskHistory() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1158px");
		mainLayout.setHeight("680px");
		
		// top-level component properties
		setWidth("1158px");
		setHeight("680px");
		
		// fromDate
		fromDate = new InlineDateField();
		fromDate.setCaption("From");
		fromDate.setImmediate(false);
		fromDate.setWidth("-1px");
		fromDate.setHeight("-1px");
		mainLayout.addComponent(fromDate, "top:40.0px;left:38.0px;");
		
		// toDate
		toDate = new InlineDateField();
		toDate.setCaption("To");
		toDate.setImmediate(false);
		toDate.setWidth("-1px");
		toDate.setHeight("-1px");
		mainLayout.addComponent(toDate, "top:40.0px;left:318.0px;");
		
		// historyTable
		historyTable = new Table();
		historyTable.setImmediate(false);
		historyTable.setWidth("1090px");
		historyTable.setHeight("423px");
		mainLayout.addComponent(historyTable, "top:237.0px;left:20.0px;");
		
		return mainLayout;
	}

}
