package org.primaldev.ppm.ui.process;


import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;

import javax.imageio.ImageIO;

import org.activiti.engine.ActivitiIllegalArgumentException;
import org.primaldev.ppm.util.ProcessUtil;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.StreamResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Window;

public class ProcessImageForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Embedded processImage;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	String processDefinitionId;
	Window mywindow;
	
	public ProcessImageForm(Window mywindow, StreamResource resource) {
		
		this.mywindow = mywindow;
		mywindow.setImmediate(true);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		processImage.setSource(resource);
		// TODO add user code here
	}


	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100%");
		setHeight("100%");
		
		// processImage
		processImage = new Embedded();
		processImage.setImmediate(true);
		processImage.setWidth("100.0%");
		processImage.setHeight("100.0%");
		processImage.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		processImage.setType(1);
		processImage.setMimeType("image/png");
		mainLayout.addComponent(processImage,
				"top:2.0px;right:2.0px;bottom:2.0px;left:2.0px;");
		
		return mainLayout;
	}
	

}
