package org.primaldev.ppm.ui.identity;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;

public class GroupManagementTab extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table groupListTable;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button removeGroup;
	@AutoGenerated
	private Button editGroup;
	@AutoGenerated
	private Button addGroup;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public GroupManagementTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:0.0px;left:0.0px;");
		
		// groupListTable
		groupListTable = new Table();
		groupListTable.setImmediate(false);
		groupListTable.setWidth("100.0%");
		groupListTable.setHeight("100.0%");
		mainLayout.addComponent(groupListTable,
				"top:60.0px;right:-3.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("60px");
		horizontalLayout_1.setMargin(false);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		horizontalLayout_1.addComponent(horizontalLayout_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("340px");
		horizontalLayout_2.setHeight("60px");
		horizontalLayout_2.setMargin(false);
		
		// addGroup
		addGroup = new Button();
		addGroup.setCaption("Add Group");
		addGroup.setImmediate(false);
		addGroup.setWidth("-1px");
		addGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(addGroup);
		horizontalLayout_2.setComponentAlignment(addGroup, new Alignment(48));
		
		// editGroup
		editGroup = new Button();
		editGroup.setCaption("Edit Group");
		editGroup.setImmediate(false);
		editGroup.setWidth("-1px");
		editGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(editGroup);
		horizontalLayout_2.setComponentAlignment(editGroup, new Alignment(48));
		
		// removeGroup
		removeGroup = new Button();
		removeGroup.setCaption("Remove Group");
		removeGroup.setImmediate(false);
		removeGroup.setWidth("-1px");
		removeGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(removeGroup);
		horizontalLayout_2
				.setComponentAlignment(removeGroup, new Alignment(48));
		
		return horizontalLayout_2;
	}

}
