package org.primaldev.ppm.ui.identity;

import java.util.UUID;

import org.activiti.engine.IdentityService;
import org.activiti.engine.ProcessEngines;
import org.activiti.engine.identity.Group;
import org.primaldev.ppm.util.OnEnterKeyHandler;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

public class GroupForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Button cancelButton;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private TextField groupNameField;
	
	Window mywindow;
	boolean newGroup;
	Group group;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public GroupForm(Window mywindow) {
		this.mywindow = mywindow;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		addClicklisteners();
		newGroup = true;
		
	}

	public GroupForm(Window mywindow, Group group) {
		this.mywindow = mywindow;
		this.group = group;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		addClicklisteners();
		newGroup = false;
		
		
	}
	
	private void addClicklisteners() {
		
		saveButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				formSubmit();
			}
		});
		
		cancelButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().removeWindow(mywindow);
			}
		});
		
		OnEnterKeyHandler onEnterHandler=new OnEnterKeyHandler(){
            @Override
            public void onEnterKeyPressed() {
            	formSubmit();
            }
        };        
        
        onEnterHandler.installOn(groupNameField);
       
	}
	
	
	private void formSubmit(){
		if (newGroup) {
			Group newGroup = getIdentityService().newGroup("newGroup");	
			newGroup.setId(UUID.randomUUID().toString());
			newGroup.setName(groupNameField.getValue());			
			getIdentityService().saveGroup(newGroup);
			
		} else {
			group.setName(groupNameField.getValue());
			getIdentityService().saveGroup(group);
		}
		UI.getCurrent().removeWindow(mywindow);
		
	}
	
	private IdentityService getIdentityService() {
		return ProcessEngines.getDefaultProcessEngine().getIdentityService();
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("380px");
		mainLayout.setHeight("240px");
		
		// top-level component properties
		setWidth("380px");
		setHeight("240px");
		
		// groupNameField
		groupNameField = new TextField();
		groupNameField.setCaption("Group Name");
		groupNameField.setImmediate(false);
		groupNameField.setWidth("100.0%");
		groupNameField.setHeight("-1px");
		groupNameField.setMaxLength(30);
		mainLayout.addComponent(groupNameField,
				"top:80.0px;right:52.0px;left:60.0px;");
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Submit");
		saveButton.setImmediate(false);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		mainLayout.addComponent(saveButton, "top:160.0px;left:60.0px;");
		
		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Cacel");
		cancelButton.setImmediate(false);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");
		mainLayout.addComponent(cancelButton, "top:160.0px;left:254.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("260px");
		label_1.setHeight("-1px");
		mainLayout.addComponent(label_1, "top:122.0px;left:60.0px;");
		
		return mainLayout;
	}

}
