package org.primaldev.ppm.ui.identity;

import java.util.List;

import org.activiti.engine.IdentityService;
import org.activiti.engine.ProcessEngines;
import org.activiti.engine.identity.Group;
import org.activiti.engine.identity.GroupQuery;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

public class GroupManagementTab extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table groupListTable;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button removeGroup;
	@AutoGenerated
	private Button editGroup;
	@AutoGenerated
	private Button addGroup;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public GroupManagementTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		initTable();
		addClickListeners();
		
	}
	
	
	private void initTable(){
		GroupQuery query = getIdentityService().createGroupQuery();
		List<Group> allGroups = query.orderByGroupId().asc().list();
		BeanItemContainer<Group> dataSource = new BeanItemContainer<Group>(
				Group.class, allGroups);
		groupListTable.setContainerDataSource(dataSource);
		groupListTable.setVisibleColumns(new String[] { "id", "name", "type" });
		updateButtonStates();		
		
	}
	
	private void addClickListeners(){
		
		editGroup.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				Group selectedGroup = (Group) groupListTable.getValue();
				if (selectedGroup != null) {
					editGroup(selectedGroup);
				}
			}
		});
		
		removeGroup.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				removeGroup();
			}
		});
		
		
		addGroup.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				addGroup();
			}
		});
	}
	
	
	private void addGroup(){
		
		Window groupFormWindow = new Window("Group Form");
		GroupForm groupForm = new GroupForm(groupFormWindow);
		groupFormWindow.setContent(groupForm);
		groupFormWindow.setSizeUndefined();
		UI.getCurrent().addWindow(groupFormWindow);
		
		groupFormWindow.addCloseListener(new CloseListener(){

			@Override
			public void windowClose(CloseEvent e) {
				initTable();
				
			} 
			
		});
	
	}
	
	private void editGroup(Group group){
		
		Window groupFormWindow = new Window("Group Form");
		GroupForm groupForm = new GroupForm(groupFormWindow,group);
		groupFormWindow.setContent(groupForm);
		groupFormWindow.setSizeUndefined();
		UI.getCurrent().addWindow(groupFormWindow);
		
		groupFormWindow.addCloseListener(new CloseListener(){

			@Override
			public void windowClose(CloseEvent e) {
				initTable();
				
			} 
			
		});
	
	}
	
	
	
	private void removeGroup() {
		Group selectedGroup = (Group) groupListTable.getValue();
		if (selectedGroup != null) {
			getIdentityService().deleteGroup(selectedGroup.getId());
			initTable();
		}
	}
	

	private void updateButtonStates() {
		boolean isGroupSelected = groupListTable.getValue() != null;
		editGroup.setEnabled(isGroupSelected);
		removeGroup.setEnabled(isGroupSelected);
	}
	
	
	private IdentityService getIdentityService() {
		return ProcessEngines.getDefaultProcessEngine().getIdentityService();
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("680px");
		mainLayout.setHeight("500px");
		
		// top-level component properties
		setWidth("680px");
		setHeight("500px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1,
				"top:0.0px;right:17.0px;left:0.0px;");
		
		// groupListTable
		groupListTable = new Table();
		groupListTable.setImmediate(false);
		groupListTable.setWidth("100.0%");
		groupListTable.setHeight("100.0%");
		mainLayout.addComponent(groupListTable,
				"top:60.0px;right:0.0px;bottom:60.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("60px");
		horizontalLayout_1.setMargin(false);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		horizontalLayout_1.addComponent(horizontalLayout_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("400px");
		horizontalLayout_2.setHeight("60px");
		horizontalLayout_2.setMargin(false);
		
		// addGroup
		addGroup = new Button();
		addGroup.setCaption("Add Group");
		addGroup.setImmediate(true);
		addGroup.setWidth("-1px");
		addGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(addGroup);
		horizontalLayout_2.setComponentAlignment(addGroup, new Alignment(48));
		
		// editGroup
		editGroup = new Button();
		editGroup.setCaption("Edit Group");
		editGroup.setImmediate(true);
		editGroup.setWidth("-1px");
		editGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(editGroup);
		horizontalLayout_2.setComponentAlignment(editGroup, new Alignment(48));
		
		// removeGroup
		removeGroup = new Button();
		removeGroup.setCaption("Remove Group");
		removeGroup.setImmediate(true);
		removeGroup.setWidth("-1px");
		removeGroup.setHeight("-1px");
		horizontalLayout_2.addComponent(removeGroup);
		horizontalLayout_2
				.setComponentAlignment(removeGroup, new Alignment(48));
		
		return horizontalLayout_2;
	}

}
