package org.primaldev.ppm.ui.identity;

import java.util.List;

import org.activiti.engine.IdentityService;
import org.activiti.engine.ProcessEngines;
import org.activiti.engine.identity.User;
import org.activiti.engine.identity.UserQuery;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

public class UserListForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button submitButton;
	@AutoGenerated
	private ListSelect userSelect;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	Window mywindow;
	
	public UserListForm(Window mywindow) {
		this.mywindow = mywindow;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		initTable();
		addClickListeners();
	}

	
	private void initTable(){
		UserQuery query = getIdentityService().createUserQuery();
		List<User> allUsers = query.orderByUserId().asc().list();
		userSelect.removeAllItems();
		for (User user : allUsers) {
			userSelect.addItem(user.getId());
		}
		
	}
	
	private void addClickListeners(){
		
		
		submitButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				formSubmit();
			}
		});
		
		
		
	}
	
	private void formSubmit(){		
		fireComponentEvent();
		UI.getCurrent().removeWindow(mywindow);
	}

	
	public String getSelectedUser(){
		return (String) userSelect.getValue();
	}
	
	private IdentityService getIdentityService() {
		return ProcessEngines.getDefaultProcessEngine().getIdentityService();
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("360px");
		mainLayout.setHeight("440px");
		
		// top-level component properties
		setWidth("360px");
		setHeight("440px");
		
		// userSelect
		userSelect = new ListSelect();
		userSelect.setCaption("Select User");
		userSelect.setImmediate(false);
		userSelect.setWidth("320px");
		userSelect.setHeight("326px");
		mainLayout.addComponent(userSelect, "top:34.0px;left:20.0px;");
		
		// submitButton
		submitButton = new Button();
		submitButton.setCaption("OK");
		submitButton.setImmediate(true);
		submitButton.setWidth("-1px");
		submitButton.setHeight("-1px");
		mainLayout.addComponent(submitButton, "top:394.0px;left:155.0px;");
		
		return mainLayout;
	}

}
