package org.primaldev.ppm.ui.identity;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;

public class UserManagentTab extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table userListTable;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button groupMemebers;
	@AutoGenerated
	private Button removeUser;
	@AutoGenerated
	private Button editUser;
	@AutoGenerated
	private Button addUser;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserManagentTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:0.0px;left:0.0px;");
		
		// userListTable
		userListTable = new Table();
		userListTable.setImmediate(false);
		userListTable.setWidth("100.0%");
		userListTable.setHeight("100.0%");
		mainLayout.addComponent(userListTable,
				"top:77.0px;right:-3.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("657px");
		horizontalLayout_1.setHeight("60px");
		horizontalLayout_1.setMargin(false);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		horizontalLayout_1.addComponent(horizontalLayout_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("400px");
		horizontalLayout_2.setHeight("60px");
		horizontalLayout_2.setMargin(false);
		
		// addUser
		addUser = new Button();
		addUser.setCaption("Add User");
		addUser.setImmediate(false);
		addUser.setWidth("-1px");
		addUser.setHeight("-1px");
		horizontalLayout_2.addComponent(addUser);
		horizontalLayout_2.setComponentAlignment(addUser, new Alignment(48));
		
		// editUser
		editUser = new Button();
		editUser.setCaption("Edit User");
		editUser.setImmediate(false);
		editUser.setWidth("-1px");
		editUser.setHeight("-1px");
		horizontalLayout_2.addComponent(editUser);
		horizontalLayout_2.setComponentAlignment(editUser, new Alignment(48));
		
		// removeUser
		removeUser = new Button();
		removeUser.setCaption("Remove User");
		removeUser.setImmediate(false);
		removeUser.setWidth("-1px");
		removeUser.setHeight("-1px");
		horizontalLayout_2.addComponent(removeUser);
		horizontalLayout_2.setComponentAlignment(removeUser, new Alignment(48));
		
		// groupMemebers
		groupMemebers = new Button();
		groupMemebers.setCaption("Group Memebership");
		groupMemebers.setImmediate(false);
		groupMemebers.setWidth("-1px");
		groupMemebers.setHeight("-1px");
		horizontalLayout_2.addComponent(groupMemebers);
		horizontalLayout_2.setComponentAlignment(groupMemebers, new Alignment(
				48));
		
		return horizontalLayout_2;
	}

}
